### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by melonedo** [melonedo/zig-tls12#2]
- [x] Extended master secret.
- [x] ~~Secp384r1.~~ (Not included in `std.crypto`.)
- [ ] Finite field Diffie-Hellman.
- [ ] RSA-PSS signature.
- [ ] Certificate revocation (https://datatracker.ietf.org/doc/html/rfc9325#name-certificate-revocation).
- [ ] Strict mode which rejects websites not following RFC 9325.
